
package com.movie.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T16:03:31.426+02:00
 * Generated source version: 3.5.7
 *
 */
public final class MovieService_MovieServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.movie.com/", "MovieServiceImplService");

    private MovieService_MovieServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MovieServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MovieServiceImplService ss = new MovieServiceImplService(wsdlURL, SERVICE_NAME);
        MovieService port = ss.getMovieServiceImplPort();

        {
        System.out.println("Invoking getMovieRating...");
        java.lang.String _getMovieRating_arg0 = "_getMovieRating_arg01171127527";
        java.lang.String _getMovieRating__return = port.getMovieRating(_getMovieRating_arg0);
        System.out.println("getMovieRating.result=" + _getMovieRating__return);


        }
        {
        System.out.println("Invoking addMovie...");
        com.movie.client.Movie _addMovie_arg0 = new com.movie.client.Movie();
        _addMovie_arg0.setId(997574277);
        _addMovie_arg0.setTitle("Title-1703056389");
        _addMovie_arg0.setYear(185715698);
        int _addMovie__return = port.addMovie(_addMovie_arg0);
        System.out.println("addMovie.result=" + _addMovie__return);


        }
        {
        System.out.println("Invoking getActorsByMovie...");
        java.lang.String _getActorsByMovie_arg0 = "_getActorsByMovie_arg0-1363637623";
        java.util.List<com.movie.client.Actor> _getActorsByMovie__return = port.getActorsByMovie(_getActorsByMovie_arg0);
        System.out.println("getActorsByMovie.result=" + _getActorsByMovie__return);


        }
        {
        System.out.println("Invoking addActor...");
        com.movie.client.Actor _addActor_arg0 = new com.movie.client.Actor();
        _addActor_arg0.setId(-1992599167);
        _addActor_arg0.setName("Name2005830254");
        int _addActor__return = port.addActor(_addActor_arg0);
        System.out.println("addActor.result=" + _addActor__return);


        }
        {
        System.out.println("Invoking getMoviesByActor...");
        java.lang.String _getMoviesByActor_arg0 = "_getMoviesByActor_arg01432451605";
        java.util.List<com.movie.client.Movie> _getMoviesByActor__return = port.getMoviesByActor(_getMoviesByActor_arg0);
        System.out.println("getMoviesByActor.result=" + _getMoviesByActor__return);


        }
        {
        System.out.println("Invoking getMovieByTitle...");
        java.lang.String _getMovieByTitle_arg0 = "_getMovieByTitle_arg0714757818";
        com.movie.client.Movie _getMovieByTitle__return = port.getMovieByTitle(_getMovieByTitle_arg0);
        System.out.println("getMovieByTitle.result=" + _getMovieByTitle__return);


        }
        {
        System.out.println("Invoking linkMovieToActor...");
        int _linkMovieToActor_arg0 = -1971411509;
        int _linkMovieToActor_arg1 = -375161490;
        boolean _linkMovieToActor__return = port.linkMovieToActor(_linkMovieToActor_arg0, _linkMovieToActor_arg1);
        System.out.println("linkMovieToActor.result=" + _linkMovieToActor__return);


        }

        System.exit(0);
    }

}
