package com.movie.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T16:03:31.493+02:00
 * Generated source version: 3.5.7
 *
 */
@WebServiceClient(name = "MovieServiceImplService",
                  wsdlLocation = "file:/D:/java/workspace/MovieProject/src/main/webapp/wsdl/movieservice.wsdl",
                  targetNamespace = "http://service.movie.com/")
public class MovieServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.movie.com/", "MovieServiceImplService");
    public final static QName MovieServiceImplPort = new QName("http://service.movie.com/", "MovieServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/java/workspace/MovieProject/src/main/webapp/wsdl/movieservice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MovieServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/java/workspace/MovieProject/src/main/webapp/wsdl/movieservice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MovieServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MovieServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MovieServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MovieServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MovieServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MovieService
     */
    @WebEndpoint(name = "MovieServiceImplPort")
    public MovieService getMovieServiceImplPort() {
        return super.getPort(MovieServiceImplPort, MovieService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieService
     */
    @WebEndpoint(name = "MovieServiceImplPort")
    public MovieService getMovieServiceImplPort(WebServiceFeature... features) {
        return super.getPort(MovieServiceImplPort, MovieService.class, features);
    }

}
