
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.movie.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-04-10T16:03:31.478+02:00
 * Generated source version: 3.5.7
 *
 */

@javax.jws.WebService(
                      serviceName = "MovieServiceImplService",
                      portName = "MovieServiceImplPort",
                      targetNamespace = "http://service.movie.com/",
                      wsdlLocation = "file:/D:/java/workspace/MovieProject/src/main/webapp/wsdl/movieservice.wsdl",
                      endpointInterface = "com.movie.client.MovieService")

public class MovieServiceImplPortImpl implements MovieService {

    private static final Logger LOG = Logger.getLogger(MovieServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#getMovieRating(java.lang.String arg0)*
     */
    public java.lang.String getMovieRating(java.lang.String arg0) {
        LOG.info("Executing operation getMovieRating");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return2026172943";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#addMovie(com.movie.client.Movie arg0)*
     */
    public int addMovie(com.movie.client.Movie arg0) {
        LOG.info("Executing operation addMovie");
        System.out.println(arg0);
        try {
            int _return = -916774093;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#getActorsByMovie(java.lang.String arg0)*
     */
    public java.util.List<com.movie.client.Actor> getActorsByMovie(java.lang.String arg0) {
        LOG.info("Executing operation getActorsByMovie");
        System.out.println(arg0);
        try {
            java.util.List<com.movie.client.Actor> _return = new java.util.ArrayList<com.movie.client.Actor>();
            com.movie.client.Actor _returnVal1 = new com.movie.client.Actor();
            _returnVal1.setId(1770691979);
            _returnVal1.setName("Name1717399248");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#addActor(com.movie.client.Actor arg0)*
     */
    public int addActor(com.movie.client.Actor arg0) {
        LOG.info("Executing operation addActor");
        System.out.println(arg0);
        try {
            int _return = 1326618727;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#getMoviesByActor(java.lang.String arg0)*
     */
    public java.util.List<com.movie.client.Movie> getMoviesByActor(java.lang.String arg0) {
        LOG.info("Executing operation getMoviesByActor");
        System.out.println(arg0);
        try {
            java.util.List<com.movie.client.Movie> _return = new java.util.ArrayList<com.movie.client.Movie>();
            com.movie.client.Movie _returnVal1 = new com.movie.client.Movie();
            _returnVal1.setId(-682297809);
            _returnVal1.setTitle("Title-800378694");
            _returnVal1.setYear(1400950056);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#getMovieByTitle(java.lang.String arg0)*
     */
    public com.movie.client.Movie getMovieByTitle(java.lang.String arg0) {
        LOG.info("Executing operation getMovieByTitle");
        System.out.println(arg0);
        try {
            com.movie.client.Movie _return = new com.movie.client.Movie();
            _return.setId(1003160609);
            _return.setTitle("Title207648372");
            _return.setYear(1458311889);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.movie.client.MovieService#linkMovieToActor(int arg0, int arg1)*
     */
    public boolean linkMovieToActor(int arg0, int arg1) {
        LOG.info("Executing operation linkMovieToActor");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
